### ISSUE TITLE
Remove duplicate event properties

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-java#44]
`path`/`line_no`/`static`/`defined_class`/`method_id` can be safely removed from HTTP and SQL events.
`defined_class`/`method_id`/`static`/`path`/`line_no` can be safely removed from any return event.

**Comment by marcuss** [comment]
dustinToday at 6:37 PM

an HTTP event is indicated by the presence of Event.httpServerRequest
SQL is indicated by presence of Event.sqlQuery
and a return event means Event.event == 'return'

**Comment by marcuss** [comment]
missing work on return events being addressed before the work of the current week.
