### ISSUE TITLE
Maven plugin alters bootclasspath

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-java#49]
In order to hook classes loaded by the bootstrap class loader, the agent jar must exist in the boot class path.

Append the following argument line:
```
-Xbootclasspath/a:$APPMAP_JAR
```

Where `$APPMAP_JAR` is the path to the appmap jar file.

**Comment by marcuss** [comment]
Corrected in this PR:
https://github.com/applandinc/appmap-java/pull/46/files#diff-1ae6ddaae8b65b6557ca0e8a7e418e5ef8f45b0adf5b12acadda9b63fdf073e3R92

**Comment by marcuss** [comment]
@dustinbyrne this probably needs to be closed by now
