### ISSUE TITLE
Fetch source file path from debug info for a class when debug info is available

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-java#56]
Implement logic that retrieves the source file location for a given class from the debug information when it is available (when class compiled with the -g option).

Current code: https://github.com/applandinc/appmap-java/blob/master/src/main/java/com/appland/appmap/output/v1/CodeObject.java#L191-L203

Acceptance:
- when debug info is available for a given class, retrieve the source file path from the debug info
- when debug info not available, use the existing heuristics

**Comment by ptrdvrk** [comment]
https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.10

**Comment by marcuss** [comment]
@ptrdvrk @dustinbyrne Few things about this ticket that I've found during development...

Taking these java files as an example, which contains an inner class declared in the same file or are annotated : [src/main/java/org/springframework/mock/web/MockFilterChain.java](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/mock/web/MockFilterChain.java)
org\springframework\mock\web\MockFilterChain$ServletFilterProxy.java
[src\main\java\co\marcuss\hipcontacts\web\rest\AccountResourceTest$1.java](https://github.com/marcuss/hipcontacts/blob/432a9448bf117884296acf0b187e04daf3439eca/src/test/java/co/marcuss/hipcontacts/web/rest/AccountResourceTest.java)


Using the SourceFile attribute just returns the actual file name but not the file path, even when called on the inner class: **MockFilterChain.java**
```
String sourceFilePath = ((SourceFileAttribute) classType.getClassFile2()
            .getAttribute("SourceFile")).getFileName()
```

The best approach I could find still takes for granted that the path will begin with "src/main/java", is this assumption safe?

Now, we will always have access to:  ``CtClass.getName()`` using this in our favor a better reliable implementation will look like:
````
String sourceFilePath =
            "src@main@java@".replaceAll("@", escapedSeparator) +
                    classType.getName().replaceAll("\\.", escapedSeparator)
                    .replaceAll("\\$\\w+", "")+ ".java"
````

Is there any other cases you could think of?

**Comment by marcuss** [comment]
btw I removed the assumption of src/main/java and nothing breaks, at least in any of my tests with pet clinic or my test app, nor with the unit test of the application, do we really need that? @dustinbyrne

**Comment by kgilpin** [comment]
I recommend that you just report the source path as reported to you by
Java, and don't prepend an assumed prefix. We can sort that out in the
client (VSCode).
