### ISSUE TITLE
Atomic finalization of streaming files to disk

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-java#78]
While streaming an AppMap to disk, the contents of the file should be written to a temporary file. Once the file has been finalized and closed, the temporary file is moved to its real destination.

- [ ] Files in progress are written to `${filename}.appmap.json.partial`
- [ ] Once finalized, `${filename}.appmap.json.partial` is moved to `${filename}.appmap.json`

**Comment by kgilpin** [comment]
See -
https://github.com/applandinc/appmap-ruby/pull/114/commits/e7381b9f104b379455f09d10b6e31030ec484b38
