### ISSUE TITLE
Bug: File access errors when recording Maven-run tests on Windows

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-java#98]
Spring petclinic project. Tests pass and get recorded fine with 1.1.2, fail with 1.2.0.

Windows 10, Oracle JDK 11

```log
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.51 s <<< FAILURE! - in org.springframework.samples.petclinic.model.ValidatorTests
[ERROR] shouldNotValidateWhenFirstNameEmpty  Time elapsed: 2.5 s  <<< ERROR!
java.lang.RuntimeException: 
java.nio.file.FileSystemException: C:\Users\petrd\AppData\Local\Temp\15604754668976555540.appmap.json -> target\appmap\org_springframework_samples_petclinic_model_ValidatorTests_shouldNotValidateWhenFirstNameEmpty.appmap.json: The process cannot access the file because it is being used by another process.

	at org.springframework.samples.petclinic.model.ValidatorTests.shouldNotValidateWhenFirstNameEmpty(ValidatorTests.java:58)
Caused by: java.nio.file.FileSystemException: 
C:\Users\petrd\AppData\Local\Temp\15604754668976555540.appmap.json -> target\appmap\org_springframework_samples_petclinic_model_ValidatorTests_shouldNotValidateWhenFirstNameEmpty.appmap.json: The process cannot access the file because it is being used by another process.

	at org.springframework.samples.petclinic.model.ValidatorTests.shouldNotValidateWhenFirstNameEmpty(ValidatorTests.java:58)

```

[spring-petclinic-win-1.1.2.log](https://github.com/applandinc/appmap-java/files/6983464/spring-petclinic-win-1.1.2.log)
[spring-petclinic-win-1.2.0.log](https://github.com/applandinc/appmap-java/files/6983465/spring-petclinic-win-1.2.0.log)

**Comment by kgilpin** [comment]
Please use -e switch as described:

> To see the full stack trace of the errors, re-run Maven with the -e
switch.

**Comment by ptrdvrk** [comment]
Log file with full exceptions

[spring-petclinic-win-with-exceptions-1.2.0.log](https://github.com/applandinc/appmap-java/files/6984588/spring-petclinic-win-with-exceptions-1.2.0.log)

**Comment by kgilpin** [comment]
What we are trying to do is move the file atomically into place, so that the contents won't appear gradually at the new location. 

https://stackoverflow.com/questions/33924479/java-nio-file-filesystemexception-the-process-cannot-access-the-file-because-it

It looks like we may have to fall back to copy-then-delete if the move fails.

**Comment by kgilpin** [comment]
@ptrdvrk let me know if you get a chance to try #100

**Comment by ptrdvrk** [comment]
@kgilpin I still see the exceptions in the logs and the tests failing with this branch's build, but unlike before, the appmaps are moved to the $TARGET/appmap folder.

**Comment by kgilpin** [comment]
Ok I can fix that

**Comment by ptrdvrk** [comment]
The fix works as expected.
